apiVersion: v1
kind: Secret
metadata:
  name: secret-appsettings
type: Opaque
data:
  appsettings.secrets.json: >-
    eyJDb25uZWN0aW9uU3RyaW5ncyI6IHsKICAgICJVc2Vyc0RiIjogIkhvc3Q9bXlwb3N0Z3Jlcy1wb3N0Z3Jlc3FsO0RhdGFiYXNlPXVzZXJzX2RiO1VzZXJuYW1lPXBvc3RncmVzO1Bhc3N3b3JkPXZ0djUzNkM1U0Y7UG9ydD01NDMyIgogIH19